library:
  source-dirs: src
tests:
  haskell-playground-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-playground
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- split
- split
- base >= 4.7 && < 5
name: haskell-playground
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/haskell-playground
license: BSD3
executables:
  haskell-playground-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-playground
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-playground#readme>
